import NavNavMenu from "./components/NavNavMenu/NavNavMenu"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <NavNavMenu /> {/* Navbar component */}
                <div>{children}</div> {/* Main content */}
            </body>
        </html>
    );
}
