import Navbar from "./components/Navbar/Navbar";
import { AuthContextProvider } from "./components/AuthContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <Navbar />
          <main style={{ paddingTop: "60px" }}>{children}</main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
