module.exports = `
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS userBets CASCADE;



CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(200) UNIQUE NOT NULL,
  email VARCHAR(200) UNIQUE NOT NULL,
  password VARCHAR(200) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE
);

CREATE TABLE userBets (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE,
  sport VARCHAR(200) NOT NULL,
  pick VARCHAR(200) NOT NULL,
  bettype VARCHAR(200) NOT NULL,
  odds DECIMAL (4,2) NOT NULL,
  amount DECIMAL (4,2) NOT NULL,
  book VARCHAR(200) NOT NULL,
  result VARCHAR(200) NOT NULL, 
  return DECIMAL (4,2) NOT NULL
)

`;
